### PR TITLE
Follow PEP8, catch praw exceptions

### PR DESCRIPTION
**Pull request by karan**

### CODE REVIEW

**Comment by jawerty** [comment]
This is a real help, thank you.

**Comment by karan** [comment]
Yeah no worries. I'll try to add more features in coming weeks if you'd like.

**Comment by jawerty** [comment]
Cool. You can look through the issues to see if there's anything you'd like to work on

**Comment by karan** [comment]
Not a lot yet. But I'll work on retrieving and displaying comments just like posts.

**Pull request merged**
