### PR TITLE
Add link types, fix class name casing, fix bug when opening links

### PR DESCRIPTION
**Pull request by mreinhardt**

### CODE REVIEW

**Comment by jawerty** [comment]
Thanks a lot. I had to patch up your request a little since it conflicted with your other PR but I am going to add it to the 0.3.1 version and make the commit.

**Comment by mreinhardt** [comment]
Oh yeah, I can rebase over the new master and change the version to this branch if you want.

**Comment by mreinhardt** [comment]
Ok, done. Rebased off of new master, resolved conflicts, and changed version in setup.py to 0.3.1

**Comment by jawerty** [comment]
Awesome. Great job, good sir. I'll upload this to pypi right now.

**Comment by mreinhardt** [comment]
Sweet!  :shipit:  I have some other ideas too, so if you want to coordinate (in case you're already tackling some) let me know!

**Comment by jawerty** [comment]
Alright, just email me at jawerty210@gmail.com

**Pull request merged**
